# Generated by Django 5.2.17 on 2026-10-02 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالک سازمان'), ('admin', 'مدیر'), ('support', 'کارشناس پشتیبانی'), ('auditor', 'حسابرسی'), ('member', 'کاربر')], default='member', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
