import { createBrowserRouter } from 'react-router-dom';
import { ProtectedRoute } from '../auth/ProtectedRoute';
import { AdminRoute } from '../auth/AdminRoute';
import { AuditRoute } from '../auth/AuditRoute';
import { AppShell } from '../components/AppShell';
import { DashboardPage } from '../pages/DashboardPage';
import { FilesPage } from '../pages/FilesPage';
import { EditorPage } from '../pages/EditorPage';
import { LoginPage } from '../pages/LoginPage';
import { AdminPage } from '../pages/AdminPage';
import { SupportPage } from '../pages/SupportPage';
import { RemoteSupportPage } from '../pages/RemoteSupportPage';
import { VideoConferencePage } from '../pages/VideoConferencePage';
import { ProfilePage } from '../pages/ProfilePage';
import { ActivityPage, MailPage, NotFoundPage, SharedPage } from '../pages/WorkspacePages';
import { TrashPage } from '../pages/TrashPage';
import { AuditPage } from '../pages/AuditPage';
import { PublicSharePage } from '../pages/PublicSharePage';
export const router = createBrowserRouter([{ path: '/login', element: <LoginPage /> }, { path: '/public/share/:token', element: <PublicSharePage /> }, { element: <ProtectedRoute />, children: [{ element: <AppShell />, children: [{ path: '/', element: <DashboardPage /> }, { path: '/files', element: <FilesPage /> }, { path: '/files/:id/edit', element: <EditorPage /> }, { path: '/support', element: <SupportPage /> }, { path: '/remote-support', element: <RemoteSupportPage /> }, { path: '/video-conference', element: <VideoConferencePage /> }, { path: '/admin', element: <AdminRoute><AdminPage /></AdminRoute> }, { path: '/profile', element: <ProfilePage /> }, { path: '/shared', element: <SharedPage /> }, { path: '/trash', element: <TrashPage /> }, { path: '/mail', element: <MailPage /> }, { path: '/activity', element: <ActivityPage /> }, { path: '/audit', element: <AuditRoute><AuditPage /></AuditRoute> }] }] }, { path: '*', element: <NotFoundPage /> }]);
