import { useCallback, useEffect, useRef, useState } from 'react';
import type { RemoteSession } from '../types/api';

type ChatMessage = { id: number | string; client_id?: string; sender: number; sender_name: string; body: string; is_staff_reply: boolean; created_at?: string };
type ConferenceEvent = { type: string; payload?: Record<string, unknown>; [key: string]: unknown };
type MediaMode = 'idle' | 'camera' | 'screen';
const defaultIce = [{ urls: 'stun:stun.l.google.com:19302' }];
function iceServers() { try { return JSON.parse(import.meta.env.VITE_ICE_SERVERS ?? JSON.stringify(defaultIce)); } catch { return defaultIce; } }

export function useRemoteConference(session: RemoteSession | null, accessToken: string | null, userId: number | null) {
  const socket = useRef<WebSocket | null>(null); const peer = useRef<RTCPeerConnection | null>(null); const localRef = useRef<MediaStream | null>(null); const candidates = useRef<RTCIceCandidateInit[]>([]);
  const [status, setStatus] = useState<'offline' | 'connecting' | 'connected' | 'failed'>('offline'); const [localStream, setLocalStream] = useState<MediaStream | null>(null); const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null); const [messages, setMessages] = useState<ChatMessage[]>([]); const [mediaMode, setMediaMode] = useState<MediaMode>('idle'); const [microphoneMuted, setMicrophoneMuted] = useState(false);
  const sessionId = session?.id; const isOfferer = Boolean(session && userId === session.requester);
  const signal = useCallback((message: object) => { if (socket.current?.readyState !== WebSocket.OPEN) return false; socket.current.send(JSON.stringify(message)); return true; }, []);
  const ensurePeer = useCallback(() => { if (peer.current) return peer.current; const connection = new RTCPeerConnection({ iceServers: iceServers() }); connection.onicecandidate = event => { if (event.candidate) signal({ type: 'webrtc.ice-candidate', payload: event.candidate.toJSON() }); }; connection.ontrack = event => setRemoteStream(previous => { const stream = previous ?? new MediaStream(); if (!stream.getTracks().some(track => track.id === event.track.id)) stream.addTrack(event.track); return stream; }); connection.onconnectionstatechange = () => { if (connection.connectionState === 'connected') setStatus('connected'); if (['failed', 'disconnected'].includes(connection.connectionState)) setStatus('failed'); }; peer.current = connection; return connection; }, [signal]);
  const negotiate = useCallback(async () => { const connection = ensurePeer(); if (!isOfferer || connection.signalingState !== 'stable') return; const offer = await connection.createOffer(); await connection.setLocalDescription(offer); signal({ type: 'webrtc.offer', payload: offer }); }, [ensurePeer, isOfferer, signal]);
  const flush = useCallback(async (connection: RTCPeerConnection) => { const pending = candidates.current.splice(0); await Promise.all(pending.map(candidate => connection.addIceCandidate(candidate))); }, []);
  const handleEvent = useCallback(async (event: ConferenceEvent) => { const connection = ensurePeer(); if (event.type === 'connection.ready') setStatus('connected'); if (event.type === 'peer.joined' && isOfferer) await negotiate(); if (event.type === 'webrtc.renegotiate' && isOfferer) await negotiate(); if (event.type === 'webrtc.offer' && !isOfferer) { await connection.setRemoteDescription(event.payload as unknown as RTCSessionDescriptionInit); await flush(connection); const answer = await connection.createAnswer(); await connection.setLocalDescription(answer); signal({ type: 'webrtc.answer', payload: answer }); } if (event.type === 'webrtc.answer' && isOfferer) { await connection.setRemoteDescription(event.payload as unknown as RTCSessionDescriptionInit); await flush(connection); } if (event.type === 'webrtc.ice-candidate') { const candidate = event.payload as unknown as RTCIceCandidateInit; if (connection.remoteDescription) await connection.addIceCandidate(candidate); else candidates.current.push(candidate); } if (event.type === 'chat.message') { const message = event.payload as unknown as ChatMessage; setMessages(items => { const existingIndex = message.client_id ? items.findIndex(item => item.client_id === message.client_id) : -1; if (existingIndex < 0 && items.some(item => item.id === message.id)) return items; if (existingIndex >= 0) return items.map((item, index) => index === existingIndex ? message : item); return [...items, message]; }); } if (event.type === 'chat.error') setStatus('failed'); }, [ensurePeer, flush, isOfferer, negotiate, signal]);
  useEffect(() => { if (!sessionId || session?.status !== 'active' || !accessToken) return; setStatus('connecting'); const base = import.meta.env.VITE_WS_URL ?? `${window.location.protocol === 'https:' ? 'wss' : 'ws'}://${window.location.host}`; const ws = new WebSocket(`${base}/ws/remote/${sessionId}/`, ['access_token', accessToken]); socket.current = ws; ws.onopen = () => { setStatus('connected'); signal({ type: 'peer.ready' }); }; ws.onmessage = event => { try { void handleEvent(JSON.parse(event.data) as ConferenceEvent).catch(() => setStatus('failed')); } catch { setStatus('failed'); } }; ws.onerror = () => setStatus('failed'); ws.onclose = () => setStatus('offline'); ensurePeer(); return () => { ws.close(1000, 'session closed'); socket.current = null; peer.current?.close(); peer.current = null; localRef.current?.getTracks().forEach(track => track.stop()); localRef.current = null; setLocalStream(null); setRemoteStream(null); setMediaMode('idle'); setMicrophoneMuted(false); }; }, [accessToken, ensurePeer, handleEvent, session?.status, sessionId, signal]);
  const stopLocalMedia = useCallback(() => { localRef.current?.getTracks().forEach(track => track.stop()); localRef.current = null; setLocalStream(null); setMediaMode('idle'); setMicrophoneMuted(false); }, []);
  const attach = useCallback(async (stream: MediaStream, mode: MediaMode) => { const connection = ensurePeer(); stopLocalMedia(); for (const track of stream.getTracks()) { const sender = connection.getSenders().find(item => item.track?.kind === track.kind); if (sender) await sender.replaceTrack(track); else connection.addTrack(track, stream); } localRef.current = stream; setLocalStream(stream); setMediaMode(mode); setMicrophoneMuted(false); if (isOfferer) await negotiate(); else signal({ type: 'webrtc.renegotiate' }); }, [ensurePeer, isOfferer, negotiate, signal, stopLocalMedia]);
  const startScreenShare = useCallback(async () => { const stream = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: true }); stream.getVideoTracks()[0]?.addEventListener('ended', stopLocalMedia, { once: true }); await attach(stream, 'screen'); }, [attach, stopLocalMedia]);
  const startCamera = useCallback(async () => { await attach(await navigator.mediaDevices.getUserMedia({ video: true, audio: true }), 'camera'); }, [attach]);
  const toggleMic = useCallback(() => { localStream?.getAudioTracks().forEach(track => { track.enabled = !track.enabled; }); setMicrophoneMuted(value => !value); }, [localStream]);
  const sendChat = useCallback((body: string) => { const clientId = crypto.randomUUID(); if (!signal({ type: 'chat.send', body, client_id: clientId })) return false; const optimistic: ChatMessage = { id: `local-${clientId}`, client_id: clientId, sender: userId ?? 0, sender_name: 'شما', body, is_staff_reply: false, created_at: new Date().toISOString() }; setMessages(items => [...items, optimistic]); return true; }, [signal, userId]);
  const stop = useCallback(() => { stopLocalMedia(); peer.current?.close(); peer.current = null; socket.current?.close(1000, 'user ended session'); setRemoteStream(null); setStatus('offline'); }, [stopLocalMedia]);
  return { status, localStream, remoteStream, messages, mediaMode, microphoneMuted, startScreenShare, startCamera, stopLocalMedia, toggleMic, sendChat, stop };
}
