export type User = {
  id: number;
  username: string;
  first_name: string;
  last_name: string;
  is_staff?: boolean;
  is_superuser?: boolean;
  is_support_online?: boolean;
  role?: 'owner' | 'admin' | 'support' | 'auditor' | 'member';
  roles?: string[];
  permissions?: Record<string, boolean | undefined>;
};
export type AuthResponse = { access: string };
export type FileItem = {
  id: number;
  name: string;
  type: 'folder' | 'pdf' | 'sheet' | 'doc' | 'image' | 'other';
  size: string;
  updated: string;
  owner: string;
  color: string;
  folder?: number | null;
};
export type Paginated<T> = { count: number; next: string | null; previous: string | null; results: T[] };
export type OnlyOfficeEditorConfig = {
  documentServerUrl: string;
  config: {
    document: { fileType: string; key: string; title: string; url: string };
    documentType: 'word' | 'cell' | 'slide';
    editorConfig: { mode?: 'edit' | 'view'; callbackUrl: string; user: { id: string; name: string } };
  };
};
export type FileVersion = { version: number; size_bytes: number; checksum: string; created_at: string; created_by: string };
export type QuotaSummary = {
  user: number;
  username: string;
  allocated_bytes: number;
  used_bytes: number;
  remaining_bytes: number;
  percent_used: number;
};
export type SupportMessage = {
  id: number;
  client_id?: string | null;
  sender: number | null;
  sender_name: string;
  body: string;
  is_staff_reply: boolean;
  is_ai?: boolean;
  created_at: string;
  pipeline?: {
    ai?: { replied?: boolean; confidence?: number; needs_human?: boolean } | null;
    notify?: { mode?: string; count?: number } | null;
  };
};
export type SupportConversation = {
  id: number;
  user: number;
  user_name: string;
  subject: string;
  status: 'open' | 'waiting_agent' | 'waiting_user' | 'ai_handling' | 'escalated' | 'closed';
  assigned_agent?: number | null;
  assigned_agent_name?: string | null;
  first_agent_response_at?: string | null;
  last_user_message_at?: string | null;
  last_agent_message_at?: string | null;
  next_escalate_at?: string | null;
  escalation_count?: number;
  ai_handled?: boolean;
  ai_confidence?: number | null;
  messages: SupportMessage[];
  created_at: string;
  updated_at: string;
  pipeline?: Record<string, unknown>;
  unread_hint?: boolean;
};
export type SupportAgentPerformance = {
  user_id: number;
  username: string;
  full_name: string;
  is_online_now: boolean;
  support_last_seen: string | null;
  reply_count: number;
  conversations_touched: number;
  avg_first_response_seconds: number | null;
  escalations: number;
  score: number;
};
export type SupportAgentPermission = {
  user: number;
  username: string;
  can_reply: boolean;
  granted_by: number | null;
  updated_at: string;
};
export type RemoteSession = {
  id: number;
  requester: number;
  requester_name: string;
  agent: number | null;
  agent_name: string | null;
  conversation: number | null;
  status: 'pending' | 'active' | 'ended' | 'expired';
  mode: 'screen_share';
  expires_at: string;
  consented_at: string | null;
  started_at: string | null;
  ended_at: string | null;
  created_at: string;
  updated_at: string;
  code?: string;
  consent_required?: boolean;
  expires_in_seconds?: number;
};
export type FileShareItem = {
  capabilities?: { view: boolean; download: boolean; copy: boolean; edit: boolean; reshare: boolean };
  can_view?: boolean;
  can_download?: boolean;
  can_edit?: boolean;
  can_reshare?: boolean;
  is_owner?: boolean;
  expires_at?: string | null;
  id: number;
  file: number;
  file_id: number;
  file_name: string;
  file_type: string;
  file_size: string;
  file_color: string;
  shared_with: number;
  shared_with_username: string;
  shared_by: number;
  shared_by_username: string;
  permission: 'view' | 'download' | 'edit';
  permission_label: string;
  message: string;
  created_at: string;
};
export type ActivityItem = {
  id: number;
  user: number;
  username: string;
  action: string;
  action_label: string;
  title: string;
  detail: string;
  target_type: string;
  target_id: number | null;
  created_at: string;
};
export type MailItem = {
  id: number;
  subject: string;
  body: string;
  sender: number;
  sender_name: string;
  recipient: number;
  recipient_name: string;
  status: string;
  status_label: string;
  priority: 'low' | 'normal' | 'high';
  priority_label: string;
  is_read: boolean;
  parent: number | null;
  created_at: string;
  updated_at: string;
};
export type UserLookup = { id: number; username: string; first_name: string; last_name: string };
export type DashboardStats = {
  files_count: number;
  shared_count: number;
  open_mails: number;
  used_bytes: number;
  allocated_bytes: number;
  used_gb: number;
  allocated_gb: number;
};
