import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import {
  Activity, Cloud, Folder, LayoutDashboard, Mail, MessageCircle, MonitorUp,
  Search, Settings, Share2, ShieldCheck, Upload, Video, LogOut, Trash2,
} from 'lucide-react';
import { useAuth } from '../auth/AuthProvider';
import { canViewAudit } from '../auth/AuditRoute';
import { NotificationBell } from './NotificationBell';
import { ThemeSwitcher } from './ThemeSwitcher';
import { OnboardingTour, resetOnboardingTour } from './OnboardingTour';
import { useState } from 'react';

const links = [{ to: '/', label: 'داشبورد', icon: LayoutDashboard }, { to: '/files', label: 'فایل‌های من', icon: Folder }, { to: '/support', label: 'پشتیبانی', icon: MessageCircle }, { to: '/remote-support', label: 'اتصال امن', icon: MonitorUp }, { to: '/video-conference', label: 'ویدیو کنفرانس', icon: Video }, { to: '/shared', label: 'اشتراک‌گذاری‌شده', icon: Share2 }, { to: '/trash', label: 'سطل زباله', icon: Trash2 }, { to: '/mail', label: 'مکاتبات', icon: Mail }, { to: '/activity', label: 'گزارش فعالیت', icon: Activity }];
const roleLabels = { owner: 'مالک سازمان', admin: 'مدیر سیستم', support: 'کارشناس پشتیبانی', auditor: 'حسابرس', member: 'کاربر فضای کاری' };
export function AppShell() { const { user, logout } = useAuth(); const navigate = useNavigate(); const [tourOpen, setTourOpen] = useState(false); const canManage = Boolean(user?.permissions?.view_admin || user?.permissions?.manage_users || user?.is_superuser || user?.role === 'admin' || user?.role === 'owner'); const visibleLinks = [...links, ...(canViewAudit(user) ? [{ to: '/audit', label: 'گزارش Audit', icon: ShieldCheck }] : []), ...(canManage ? [{ to: '/admin', label: 'سطح دسترسی‌ها', icon: ShieldCheck }] : [])]; return <div className="app-shell"><aside className="sidebar glass"><div className="brand"><div className="brand-mark"><Cloud size={20} /></div><div><strong>دفتر ابری</strong><small>Cloud Office</small></div></div><button className="new-button" onClick={() => navigate('/files')}><Upload size={17} />آپلود فایل</button><nav>{visibleLinks.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'}><Icon size={19} /><span>{label}</span></NavLink>)}</nav><div className="sidebar-bottom sidebar-bottom--actions"><button type="button" onClick={() => navigate('/profile')}><Settings size={16} />تنظیمات کاربر</button><button type="button" onClick={() => { resetOnboardingTour(); setTourOpen(true); }}>راهنمای شروع</button><button type="button" className="logout-button" onClick={async () => { await logout(); navigate('/login'); }}><LogOut size={16} />خروج</button></div></aside><main className="main"><header className="topbar"><div className="search"><Search size={18} /><input placeholder="جست‌وجو در دفتر ابری…" aria-label="جست‌وجو" /></div><div className="top-actions"><ThemeSwitcher compact /><NotificationBell /><button type="button" className="avatar" onClick={() => navigate('/profile')} title="پنل کاربر">{user?.first_name?.[0] ?? 'م'}</button><div className="user-name"><b>{user ? `${user.first_name} ${user.last_name}` : 'مریم رضایی'}</b><small>{user ? roleLabels[user.role ?? 'member'] : 'کاربر فضای کاری'}</small></div></div></header><div className="content"><Outlet /></div></main><div className="mobile-nav">{visibleLinks.slice(0, 5).map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'}><Icon size={19} /><span>{label}</span></NavLink>)}</div><button type="button" className="floating-support" onClick={() => navigate('/support')} title="چت پشتیبانی" aria-label="چت پشتیبانی"><MessageCircle size={22} /></button>
      <OnboardingTour forceOpen={tourOpen} onClose={() => setTourOpen(false)} />
    </div>; }
