# Generated by Django 5.2.17 on 2026-10-01 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending consent'), ('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('screen_share', 'Screen share')], default='screen_share', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_sessions_joined', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_sessions', to='support.conversation')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sessions_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
